### PR TITLE
Update api.texi

### PR DESCRIPTION
**Pull request by rns**
typo fixes

### CODE REVIEW

**Comment by jeffreykegler** [comment]
Thanks!  But note I'll undo the second correction -- precomputed grammars cannot have the terminal settings changed, so the text is correct as it stands, I think.

**Comment by rns** [comment]
Yes, the second correction applies to `marpa_g_symbol_is_terminal_set()` as I now see, so it's rightly undone. However, return value of `marpa_g_symbol_is_terminal()` is left undocumented, but it deserves filing a separate issue, so I will.

**Comment by rns** [comment]
Suggested edit: if the grammar g is precomputed (or, in the case of marpa_g_symbol_is_terminal(), not precomputed) or on other failure, -2

**Comment by jeffreykegler** [comment]
Now that I think things over, it's not clear to me why `marpa_g_symbol_is_terminal()` should only be available after the grammar is precomputed -- if you can set a value, you should be able to query it.

**Comment by jeffreykegler** [comment]
The just referenced commit combines a doc and a code change, to address this issue.

**Comment by rns** [comment]
The tests are added/updated to match the doc.

**Pull request merged**
