### PR TITLE
pkg-config

### PR DESCRIPTION
**Pull request by dabrahams**
I'd like to stop maintaining a fork of libMarpa if possible…

### CODE REVIEW

**Comment by jeffreykegler** [comment]
I read this as a request to move the branch I created for #87 into the master branch.  This has not been happening because I have prioritized #92.  Progress on #92, in turn, has been slowed, and at points almost halted, because I turned out to be much sicker than I expected, and at points could only sit at the terminal for an hour or two a day.

So, I am working at #92 as much as I prudently can, and once that is done, my next priority is #87.

**Comment by dabrahams** [comment]
understood, thanks.  Well, it's a request to merge rather than move.  Most people find PRs a convenient way to do that, and to keep track of the work in progress, and to close the related issue.  If it's inconvenient for you to have this open, though, feel free to close it of course.

**Comment by jeffreykegler** [comment]
@dabrahams I greatly appreciate your interest and support, and regret that these issues are being cleared more slowly than you and I would like.  What I'll likely do when I come back to this is a "pseudo-merge", in order to properly record the contribution, and then move forward to the long delayed #87.

**Comment by jeffreykegler** [comment]
I am resuming work on #87 and, accordingly, closing this PR.  Further discussion can take place there.

**Pull request closed without merging**
