### PR TITLE
Add pkg-config support

### PR DESCRIPTION
**Pull request by dabrahams**
This hasn't made a difference for me (yet), but it appears to be correct.

### CODE REVIEW

**Comment by dabrahams** [comment]
Correction: it is making a difference, and it works.

**Comment by jeffreykegler** [comment]
I am grateful for your efforts, but I considered using pkg-config some years ago, and rejected the idea because portability is an obsession for me with libMarpa, and every new tool is a point of failure.

Since then I've encountered the Lua installation methods which made me realize that I didn't need CMake -- that CMake itself is an unnecessary point of failure.  My highest priority is to avoid the risk that change of any kind imposes, so there is no immediate plan to remove CMake.  But if I have to move, CMake removal is the direction I would take.

For these reasons, my inclination is to not incorporate this change in the upstream.  I'll let this pull request sit for a couple of days for discussion.  If nothing occurs that changes my mind, I will close it.

I realize that this highly conservative policy of mine may be more restrictive than some libMarpa users can live with, but these users can, albeit at the cost of some trouble, fork.  Some authors regard a fork as an unfriendly act, but I am most definitely not one of those people, and i am happy to help to make forks successful.  Thanks!

**Comment by dabrahams** [comment]
Including pkg-config support has nothing to do with the way the library is configured/built/installed; I would want it no matter what system was used. Having a .pc file installed makes it possible for other tools and build systems to consume the installed library automatically.  In particular, my [Homebrew installation](https://github.com/Homebrew/homebrew-core/pull/97567) can only be consumed by the Swift Package manager automatically if there is a .pc file.  Otherwise, each project that consumes the library needs to specify its own linker and include paths.  More detail can be found in [this post](https://forums.swift.org/t/spm-brew-packaged-library-where-do-include-lib-paths-come-from/).

If you want libmarpa to be adopted, having pkg-config support can really help.  Without it, vending a wrapper or simply a package that doesn't impose configuration heck for downstream users can become much more difficult.

**Comment by jeffreykegler** [comment]
I will take another, careful, look at this, primarily to try to assure myself that the change is safe.  Thanks!

**Comment by jeffreykegler** [comment]
I'm currently looking into standards for usage of pkg-config with CMake.  I take it your patch has no `include(FindPkgConfig)` line because you are not changing CMake to use pkg-config, just to create the file to be installed, which will be available for those who want and can use it, and for the others should be mostly inert.

I take it that the

`install(FILES "${PROJECT_BINARY_DIR}/libmarpa.pc" DESTINATION "lib/pkgconfig/")`

command will create a `lib/pkgconfig` directory if none exists.

I will ask the Marpa IRC channel their opinions, advice, etc.  That won't happen until Monday, because the channel tends to get less attention on the weekend.

**Comment by zmughal** [comment]
I agree that a `.pc` file would be useful. I look for one in every library that I use and a `.pc` file can be generated by any build system (even a hand-rolled one), not just CMake. It just needs to install to the correct location if installed to the system (`pc_path`) or added to the `PKG_CONFIG_PATH` environment variable if installed elsewhere.

**Comment by dabrahams** [comment]
That's all correct.

**Comment by jeffreykegler** [comment]
I did a manual pull of this branch for testing.

**Comment by jeffreykegler** [comment]
With the manual pull, I am closing this.  Further discussion can take place as a new issue.

**Pull request closed without merging**
