### PR TITLE
Public methods on trivial grammar

### PR DESCRIPTION
**Pull request by rns**
This does the set up for testing of public methods for trivial grammar.

BTW, one test `marpa_g_symbol_is_start()` is failing. Would you please check that it's not a false positive? I'd try a fix in the next PR then per IRC discussion.

### CODE REVIEW

**Comment by jeffreykegler** [comment]
Thanks!!!

**Comment by jeffreykegler** [comment]
Re marpa_g_symbol_is_start() -- this looks complicated -- I think you'd better leave this one to me, at least for a preliminary analysis.  It looks like, when it comes to the start symbol, I'm doing the same thing in several ways.  I need to figure out what I really intend here.

**Comment by rns** [comment]
Ok, I'll proceed with other methods.

**Comment by jeffreykegler** [comment]
I just created a separate issue to deal with `marpa_g_symbol_is_start()`

**Pull request merged**
