### PR TITLE
add menu item for Events

### PR DESCRIPTION
**Pull request by rns**
Fix `<a href="#Ranks">11.8 Events</a>` link in http://jeffreykegler.github.io/Marpa-web-site/libmarpa_api/stable/api_one_page.html

### CODE REVIEW

**Comment by jeffreykegler** [comment]
I'm probably going to just let this sit until I fork Kollos's Libmarpa.

**Comment by rns** [comment]
Sure, that's fine with me.

**Comment by jeffreykegler** [comment]
Thanks!  I decided that rather that it's probably easiest to tag my attempted fork point, and let git do what it does, rather than artificially hold back changes.

**Comment by rns** [comment]
Great!

**Pull request merged**
