### PR TITLE
marpa_r_current_earleme()

### PR DESCRIPTION
**Pull request by rns**
a nit in `subj`.

### CODE REVIEW

**Comment by jeffreykegler** [comment]
The error code `MARPA_ERR_RECCE_NOT_STARTED` already exists, I think.

**Comment by rns** [comment]
Sure, the patch makes `marpa_r_current_earleme()` set that code and return -1 if called before `marpa_r_start_input()`.

**Comment by jeffreykegler** [comment]
The procedure for adding new error codes, and performing various checks & tests on them, is described in [the work/public README](https://github.com/jeffreykegler/libmarpa/blob/master/work/public/README)

**Comment by jeffreykegler** [comment]
My apologies!  I misread.  Thanks!

**Pull request merged**
